# Generated by Django 2.0 on 2020-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_R_P_students', '0007_auto_20200715_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='STATUS',
            field=models.CharField(default='NO QUERY', max_length=100),
        ),
    ]
