# Generated by Django 2.0 on 2020-07-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_R_P_students', '0008_students_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TEACHER_NAME', models.CharField(max_length=200)),
                ('PASSWORD', models.CharField(default='KIET123', max_length=250)),
            ],
        ),
    ]
