# Generated by Django 2.0 on 2020-07-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_R_P_students', '0011_auto_20200718_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='USER_NAME',
            field=models.CharField(default='NULL', max_length=250, unique=True),
        ),
    ]
